### ISSUE TITLE
If two units are in the same position you can not move them

### ISSUE THREAD

**Issue by Jergar92** [GangBug/AgeofEmpiresII#22]
**Build:**
0.3.5

**Type:**
Code
**Description:**
If two units are in the same position you can not move them

**Severity:**
[ ]Critical   
[ x]Major   
[ ]Minor   

**Priority:**
[ ]Urgent  
[x ]High  
[ ]Normal  
[ ]Low  

**Steps to reproduce:**
Spawn units
Gets two units to be placed at the same point
Then you can't move them
**Frequency:**
1/1

**Screenshot(optional):**

**Comment by Yulna** [comment]
In my case it's needed more than 5 units for it to happen
