### ISSUE TITLE
Selected Units

### ISSUE THREAD

**Issue by PereRifa** [GangBug/AgeofEmpiresII#25]
**Build:**
v0.3.5

**Type:**
Polish

**Description:**
You don't know which are the selected units, maybe a mark/circle or something could fix it.

**Severity:**
[ ]Critical   
[ ]Major   
[x]Minor   

**Priority:**
[ ]Urgent  
[x]High  
[ ]Normal  
[ ]Low  

**Steps to reproduce:**
Select Unit left click and drag

**Frequency:**
(1/1)

**Screenshot(optional):**

**Comment by adriancl1** [comment]
We added life bars that show up only on selected units now.
