### ISSUE TITLE
Crash when exiting

### ISSUE THREAD

**Issue by adriancl1** [GangBug/AgeofEmpiresII#3]
**Status**: Solved
**Category**: Code
**Priority**: Critical
**Severity**: Crash
**Frequency**: Always if steps followed
**Description**:
When you exit the program it always crashes.

**Steps**:
1- Start the game.
2-Close the game.

**Screenshot**:
![fatalbug](https://cloud.githubusercontent.com/assets/17147051/24238997/78d2083a-0fac-11e7-9cae-f45507377b7d.PNG)

**Comment by CapitanLiteral** [comment]
Can you specify how you closed the game? We cant find this crash in our code 🤔
