### ISSUE TITLE
HUD doesn't adapt to fullscreen

### ISSUE THREAD

**Issue by carcasanchez** [GangBug/AgeofEmpiresII#33]
**Build: 0.3.5**

**Type: Aesthetic**

**Description: HUD size doesn't match with  screen size when put in fullscreen**

**Severity:**
[ ]Critical   
[ ]Major   
[ x]Minor   

**Priority:**
[x ]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**Steps to reproduce:**
-Open config.xml
-Set Fullscreen value to true
-Start the game

**Frequency:**
-Always

**Screenshot(optional):**

**Comment by adriancl1** [comment]
You need to use your screen's resolution and the set fullscreen to true.
