### ISSUE TITLE
Crash when pressing M and Spacebar

### ISSUE THREAD

**Issue by adriancl1** [GangBug/AgeofEmpiresII#4]
**Status**: Closed
**Category**: Code
**Priority**: Critical
**Severity**: Crash
**Frequency**: Always if steps followed
**Description**:
When you press M or spacebar it crashes.

**Steps**:
1- Start the game.
2- Press M or Spacebar.

**Screenshot**:
![bug2](https://cloud.githubusercontent.com/assets/17147051/24239136/f7c723b4-0fac-11e7-9037-2f7056277a51.PNG)

**Comment by CapitanLiteral** [comment]
Ok, we got your feedback and will try to solve it 😄
