### ISSUE TITLE
Crashes when creating archer after return to title screen

### ISSUE THREAD

**Issue by carcasanchez** [GangBug/AgeofEmpiresII#9]
Status: New
Category: Code
Priority: Major
Severity: Crash
Frequency: Always if steps followed
Description:
When you create an archer after returning to title screen and reload scene.
Branch: Vertical Slice

Steps:
1- Start the game.
2- Press F10.
3-Re-start the game
4-Press 3

**Comment by Josef212** [comment]
After step 3 scene is not loaded properly.
Step 4 can be also achieved clicking on Okey button
![bug1](https://cloud.githubusercontent.com/assets/9293743/24613519/d4c6a8be-1888-11e7-870c-fa4efc210cc5.png)
